name = "embed_utils"
description = "Utilities for bare-metal, cross compilation in Ada"
version = "0.1.0-dev"

authors = ["José Antonio Verde Jiménez"]
maintainers = ["José Antonio Verde Jiménez <joseaverde@protonmail.com>"]
maintainers-logins = ["joseaverde"]
licenses = "EUPL-1.2"
website = ""
tags = []
