name = "seizure_detector_fixed"
description = "SPARK-proved fixed point implementation of seizure detection algorithm"
version = "0.6.0"

authors = ["José Antonio Verde Jiménez"]
maintainers = ["José Antonio Verde Jiménez <joseaverde@protonmail.com>"]
maintainers-logins = ["joseaverde"]
licenses = "EUPL-1.2"
website = ""
tags = []

[configuration.variables]
Target = {type = "Enum", default = "native", values = ["native", "esp32c3", "rpi"]}
Parallel = {type = "Enum", default = "True", values = ["False", "True"]}

[build-switches]
"*".ada_version    = "Ada2022"
"*".style_checks = [ "-gnaty3"          # Indentation to 3
                   , "-gnatya"          # Check attribute casing
                   , "-gnatyA"          # Check array attribute indexes
                   , "-gnatyb"          # No blanks at end of lines
                   , "-gnatyd"          # No DOS line terminators
                   , "-gnatye"          # end/exit labels present
                   , "-gnatyf"          # No form feeds or vertical tabs
                   , "-gnatyh"          # No horizontal tabs
                   , "-gnaty-I"         # `in' is required in parameters
                   , "-gnatyk"          # Check casing rules for keywords
                   , "-gnatyL5"         # Maximum nesting level
                   # , "-gnatyM79"        # Maximum 79 characters.
                   , "-gnatyn"          # Check casing of package Standard identifiers
                   , "-gnatyO"          # Check overriding indicators
                   , "-gnatyp"          # Check pragma casing
                   , "-gnatyr"          # Check casing for identifier references
                   # , "-gnatyt"          # Check token separation rules
                   , "-gnatyu"          # Check no unnecessary blank lines
                   , "-gnatyx"          # Check extra parenthesis around conditionals
                   ]

[[depends-on]]
gnatprove = "^13.0.0"

