CREATE (WORD-BUFFER) 48 CHARS ALLOT
: READ-CHAR PAD 1 STDIN READ-FILE THROW IF PAD C@ THEN ;
: SPACE? ( ch -- b ) DUP BL =  OVER 10 = OR  SWAP 13 = OR ;
: SKIP-SPACES BEGIN READ-CHAR DUP SPACE? WHILE DROP REPEAT ;
: READ-WORD (WORD-BUFFER) 0 OVER SKIP-SPACES BEGIN
      DUP SPACE? INVERT
   WHILE
      OVER C! CHAR+ SWAP 1+ SWAP READ-CHAR
   REPEAT 2DROP ;

: READ-NUMBER 0. READ-WORD >NUMBER 2DROP DROP ;
: READ-FLOAT READ-WORD >FLOAT INVERT IF 10 ABORT THEN ;

