REQUIRE input.fth 
[UNDEFINED] F, [IF]  : F, ALIGNED HERE FLOAT ALLOT F! ;  [THEN]
: READ-F: CREATE READ-FLOAT F, DOES> F@ ;
: READ-SIGNAL READ-NUMBER DUP FLOATS 0 ?DO
      READ-FLOAT F, FLOAT +LOOP ;
READ-F: PSD-1-MIN    READ-F: PSD-2-MIN    READ-F: PSD-3-MIN
READ-F: PSD-1-MAX    READ-F: PSD-2-MAX    READ-F: PSD-3-MAX
READ-F: ENERGY-MIN   READ-F: MAX-DIST-MIN READ-F: D_MAX_C
READ-F: ENERGY-MAX   READ-F: MAX-DIST-MAX

VARIABLE SIGNAL-SIZE CREATE SIGNAL  READ-SIGNAL SIGNAL-SIZE !

