name = "float_algorithms"
description = "SPARK-proved algorithms for seizure detection (floating point)"
version = "0.1.0-dev"

authors = ["José Antonio Verde Jiménez"]
maintainers = ["José Antonio Verde Jiménez <joseaverde@protonmail.com>"]
maintainers-logins = ["joseaverde"]
licenses = "EUPL-1.2"
website = ""
tags = []

executables = ["main"]

[configuration.variables]
Real_Type = {type = "Enum", default = "Double", values = ["Single", "Double"]}

[[depends-on]]
gnatprove = "^14.1.1"

[[depends-on]]
common_seizure_detector = "~0.1.0-dev"

[[pins]]
common_seizure_detector = { path='../common' }

[build-switches]

"*".ada_version    = "Ada2022"
"*".style_checks = [ "-gnaty3"          # Indentation to 3
                   , "-gnatya"          # Check attribute casing
                   , "-gnatyA"          # Check array attribute indexes
                   , "-gnatyb"          # No blanks at end of lines
                   , "-gnatyC"          # Comment format: 1 space (-- comment)
                   , "-gnatyd"          # No DOS line terminators
                   , "-gnatye"          # end/exit labels present
                   , "-gnatyf"          # No form feeds or vertical tabs
                   , "-gnatyh"          # No horizontal tabs
                   , "-gnaty-I"         # `in' is required in parameters
                   , "-gnatyk"          # Check casing rules for keywords
                   # , "-gnatyL6"         # Maximum nesting level
                   , "-gnatyM79"        # Maximum 79 characters.
                   , "-gnatyn"          # Check casing of package Standard identifiers
                   , "-gnatyO"          # Check overriding indicators
                   , "-gnatyp"          # Check pragma casing
                   , "-gnatyr"          # Check casing for identifier references
                   # , "-gnatyt"          # Check token separation rules
                   , "-gnatyu"          # Check no unnecessary blank lines
                   , "-gnatyx"          # Check extra parenthesis around conditionals
                   ]
