[package]
name = "uc3m-thesis-ieee"
version = "0.4.0"
entrypoint = "lib.typ"
authors = [
    "Luis Daniel Casais Mezquida <@rajayonin>",
    "José Antonio Verde Jimenez <@joseaverde>",
    "Jorge Lázaro Ruiz <@JorgeyGari>",
]
license = "MIT"
description = "Typst Bachelor Thesis template of the Universidad Carlos III de Madrid, IEEE style"
repository = "https://github.com/guluc3m/uc3m-thesis-ieee-typst"
keywords = ["uc3m", "thesis"]
categories = ["paper", "thesis", "report"]
exclude = [".github", "docs", "examples", ".vscode", "template/main.pdf"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
